name: demo_wether_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  dio: ^4.0.4
  intl: ^0.17.0
  syncfusion_flutter_charts: ^19.4.54
  flutter_svg: ^1.0.1
  geocoding: ^2.0.2
  geolocator: ^8.2.0
  circular_menu: ^1.2.3
  fluttertoast: ^8.0.8
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  image_path: "assets/images/applogo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: flutterfonts
      fonts:
            - asset: assets/fonts/flutterfonts.ttf
